---
name: "OIDC Integration Test"
on:
  workflow_dispatch:
jobs:
  test:
    name: "Test"
    runs-on: "ubuntu-24.04"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955" # v4.3.0
      - name: "Save user id"
        id: user_id
        run: |
          echo "user_id=$(id -u)" >> $GITHUB_OUTPUT
      - name: "Save group id"
        id: group_id
        run: |
          echo "group_id=$(id -g)" >> $GITHUB_OUTPUT
      - name: "Set up buildx"
        uses: "docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435" # v3.11.1
      - name: "Run tests"
        run: |
          ./run.sh
        shell: "bash"
        working-directory: "tests/integration"
        env:
          USER_ID: ${{ steps.user_id.outputs.user_id }}
          GROUP_ID: ${{ steps.group_id.outputs.group_id }}
          UBUNTU_VERSION: "24.04"
          PYTHON_VERSION: "3.9"
          COMPOSE_DOCKER_CLI_BUILD: 1
          DOCKER_BUILDKIT: 1
          PYTEST_ADDOPTS: -vv
