name: "Push images to Docker Hub"
on: workflow_dispatch
jobs:
  build:
    name: "Build and push images"
    runs-on: "ubuntu-24.04"
    strategy:
      fail-fast: false
      matrix:
        component:
          - archivematica-dashboard
          - archivematica-mcp-client
          - archivematica-mcp-server
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955" # v4.3.0
      - name: "Set up buildx"
        uses: "docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435" # v3.11.1
      - name: "Log in to Docker Hub"
        uses: docker/login-action@184bdaa0721073962dff0199f1fb9940f07167d1 # v3.5.0
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: "Build and push ${{ matrix.component }}"
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6.18.0
        with:
          context: .
          push: true
          load: true
          file: ./hack/Dockerfile
          target: ${{ matrix.component }}
          tags: artefactual/${{ matrix.component }}:latest
